### PR TITLE
Bug fix, changed which variable to reference 

### PR DESCRIPTION
**Pull request by adamsclafani**
changes as per the discussion [here](https://github.com/iiab/iiab/pull/2773#issuecomment-839403620)

### CODE REVIEW

**Comment by jvonau** [comment]
For the noted [AttributeError: 'Response' object has no attribute 'status'](https://github.com/iiab/iiab/pull/2773#issuecomment-832847178) and changing variable discussed [here](https://github.com/iiab/iiab/pull/2773#issuecomment-833274467)

**Comment by holta** [comment]
> For the noted [AttributeError: 'Response' object has no attribute 'status'](https://github.com/iiab/iiab/pull/2773#issuecomment-832847178) and changing variable discussed [here](https://github.com/iiab/iiab/pull/2773#issuecomment-833274467)

@c-w @sbathgate what reviews are appropriate, in order to move forward merging this PR?

Thank you for clarifying!

**Review by sbathgate — APPROVED** [review]
LGTM

**Comment by sbathgate** [comment]
We typically operate with a second view approval method. This one is obviously straightforward so you can merge when ready.

**Comment by holta** [comment]
> We typically operate with a second view approval method. This one is obviously straightforward so you can merge when ready.

Thank much @sbathgate.

Does @adamsclafani have commit/merge privileges?

**Comment by sbathgate** [comment]
> > We typically operate with a second view approval method. This one is obviously straightforward so you can merge when ready.
> 
> Thank much @sbathgate.
> 
> Does @adamsclafani have commit/merge privileges?

He should do. But I'll merge this just to get things moving for you.

**Comment by nzola** [comment]
Sorry! I accidentally clicked Delete branch. I have restored it.

**Pull request merged**
